### PR TITLE
More Changes

### PR DESCRIPTION
**Pull request by johnkeller101**
- Header injection per request
- Prevent adding base url to previous complete urls
- Additional logging for decorate function
- Make `VoidReply` public to prevent decoding issues
- Make `httpClient` public so there is only one reference (prevent `Zone5 = nil` error)

### CODE REVIEW

**Comment by jeanhall** [comment]
I've merged this into my local branch and am looking at it.

Is your method of adding headers to each request sufficient for your requirements?

**Comment by johnkeller101** [comment]
@jeanhall I keep getting this error printed in the logs after successful web requests, any ideas?
```
writeDBwithCachedResponse - Invalid protocol-property list - CFURLRequestRef. protoProps={
    requiresAccessToken = 1;
    taskType = "Zone5.URLSessionTaskType.data";
    zone5 = "Zone5.Zone5";
}
```

**Comment by jeanhall** [comment]
> @jeanhall I keep getting this error printed in the logs after successful web requests, any ideas?
> 
> ```
> writeDBwithCachedResponse - Invalid protocol-property list - CFURLRequestRef. protoProps={
>     requiresAccessToken = 1;
>     taskType = "Zone5.URLSessionTaskType.data";
>     zone5 = "Zone5.Zone5";
> }
> ```

**Comment by jeanhall** [comment]
hmm that's interesting - Those are the 3 items being added to the Request meta info. I'll investigate.

**Comment by jeanhall** [comment]
> hmm that's interesting - Those are the 3 items being added to the Request meta info. I'll investigate.

This is the problem causing that error: "NSURLProtocol's setProperty:forKey:inRequest: should be property list serializable, although that's not explicitly stated in Apple's documentation."

I'll make a change to clean up all the meta info before executing the request. I am only using to be pass information from the original request to the interceptor so it doesn't need to persist after the interceptor anyway.

**Pull request merged**
